export function exception() {
  try {
  } catch (error) {
    return error;
  }
}
